### ISSUE TITLE
start ordering of workgroups with 1 instead of 0?

### ISSUE THREAD

**Issue by vinhdizzo** [tlh/workgroups.el#10]
Hi,

I know this is a matter of personal taste, but would it be too much to ask for an option that starts the workgroup number at 1 instead of 0?  0 would thus refer to the 10'th workgroup.  My preference is because I use the numbers on top of the QWERTY keys, and 1 is the first one.

**Comment by tlh** [comment]
I'm a stickler for zero-based indexing, but you can rebind the commands if you wish.

**Comment by vinhdizzo** [comment]
I don't mean just the keybindings.  A workgroup always starts at 0 (the left most).  I'd just like that to be 1.  But I guess your preference is 0.
