### ISSUE TITLE
Faces are illegible on light displays

### ISSUE THREAD

**Issue by purcell** [tlh/workgroups.el#12]
The current face defs specify light-colored `:foreground`s on color displays, but these are illegible when using a theme with a light background.

One solution would be to add the background class specifier to the faces so that those light foreground colors would only be applied when the display has a dark background.

A better and more general solution, and one which I would strongly advise, would be to follow the pattern of many other emacs packages (including org), and use `:inherit` to derive your faces from a variety of built-in faces, e.g. `font-lock-keyword-face`. This way, the `workgroups` faces will look okay by default with any theme, but can still be overridden if desired.

Keep up the great work!

Cheers,

-Steve

**Comment by tlh** [comment]
Hey there -- thanks.  This has been fixed in the upcoming 1.0.0 release (all faces have been redefined to inherit from font-lock-foo faces),  I just haven't gotten around to updating the master branch.

**Comment by purcell** [comment]
Great - I didn't spot that!

**Comment by dabrahams** [comment]
Is that in the "experimental" branch?  When do you plan to release it?  Thanks!
