### ISSUE TITLE
emacsclient over SSH hangs with open workgroups

### ISSUE THREAD

**Issue by ghost** [tlh/workgroups.el#2]
I use Emacs 23.2.1 on a 32-bit Debian box as my remote Emacs daemon.  After connecting over ssh, I add new emacsclients using a script which runs
    emacsclient -c --alternate-editor="" $@

If I update and save the working state of all workgroups (C-z U and C-z C-s), I can safely close the emacsclient frame with `save-buffers-kill-terminal' with no ill effects.  However, if I forget to follow this procedure, or if my connection is interrupted, I can end up unable to access my emacs daemon--even resetting it with emacsclient --eval (server-start) becomes impossible.

Will add more info as I continue to poke the issue from this end.

**Comment by tlh** [comment]
I wasn't able to reproduce this, but wgreenhouse said it wasn't as dire as he thought.  Something broke terminal refresh, but the daemon was still accessible.  I'm closing this, but will reopen with further info if necessary.
