### ISSUE TITLE
wg-prefix-key doesn't work after a while

### ISSUE THREAD

**Issue by vinhdizzo** [tlh/workgroups.el#3]
Regardless of what wg-prefix-key is defined, it stops working after a while.  Don't know if this specific to me.  If I leave the default, after a while, C-z suspends emacs.  For other keys, it shows them as undefined.

**Comment by vinhdizzo** [comment]
neve mind.  viewing a wg save file turns off wg.

**Comment by tlh** [comment]
What form are you using to turn on workgroups?

It sounds like you're using (workgroups-mode), which will toggle
workgroups on or off every time it's evaluated.  So if you, say,
reload your .emacs, it will turn workgroups off, returning
wg-prefix-key to its previous definition (suspend-frame
for "C-z", or probably undefined for something like "C-c w")

If this is the case, use (workgroups-mode t) instead.
