### ISSUE TITLE
window configuration not save properly with latex files?

### ISSUE THREAD

**Issue by vinhdizzo** [tlh/workgroups.el#4]
I have a few latex files (_.tex) files opened in one window configuration.  wg-save does not include the files:
(-_-workgroups-_\- ((type . workgroup) (uid . 1) (name . "test") (wconfig (type . wconfig) (left . 0) (top . 58) (width . 149) (height . 35) (sbars) (sbwid . 0) (wtree (type . window) (edges 0 0 151 34) (bname . "_scratch_") (fname) (point . 1) (mark) (markx) (wstart . 1) (hscroll . 0) (sbars 16 0 t nil) (margins nil) (fringes 9 9 nil) (selwin . t) (mbswin)))) ((type . workgroup) (uid . 0) (name . "temp") (wconfig (type . wconfig) (left . 0) (top . 58) (width . 149) (height . 35) (sbars) (sbwid . 0) (wtree (type . wtree) (dir) (edges 0 0 151 34) (wlist ((type . window) (edges 0 0 76 34) (bname . "init.el") (fname . "/home/vinh/.emacs.d/init.el") (point . 98030) (mark . 97998) (markx) (wstart . 97608) (hscroll . 0) (sbars 16 0 t nil) (margins nil) (fringes 9 9 nil) (selwin . t) (mbswin)) ((type . window) (edges 76 0 151 34) (bname . "_scratch_") (fname) (point . 1) (mark) (markx) (wstart . 1) (hscroll . 0) (sbars 16 0 t nil) (margins nil) (fringes 9 9 nil) (selwin) (mbswin)))))) ((type . workgroup) (uid . 2) (name . "hello") (wconfig (type . wconfig) (left . 0) (top . 58) (width . 149) (height . 35) (sbars) (sbwid . 0) (wtree (type . window) (edges 0 0 151 34) (bname . "_scratch*") (fname) (point . 1) (mark) (markx) (wstart . 1) (hscroll . 0) (sbars 16 0 t nil) (margins nil) (fringes 9 9 nil) (selwin . t) (mbswin)))))

Can you help?

**Comment by tlh** [comment]
You just need to run wg-update-workgroup (C-z u) or wg-update-all-workgroups (C-z U) before you save your workgroups to file.  Read the section "Base and Working Configs" here:

https://github.com/tlh/workgroups.el

**Comment by vinhdizzo** [comment]
Ahh I see.  I prefer not to have a working and base config distinction.  Is it possible to make the working config equal to the base config all the time?  I suppose it'll require the use of hooks.

By doing this, I guess the features would be identical to escreen, except window configurations can be saved, and they can persist through multiple emacs instances.

**Comment by tlh** [comment]
That's a possibility, but I'd prefer not to.  One complication occurs when you've got multiple frames visiting the same workgroup.  If they're both auto-updating the same base-config, you're never quite sure what the state of the base-config that gets saved to a file is.

If I were to automate a step from update-then-save process, it'd probably be the save part, so that changes to a workgroup's base-config or other parameters would trigger autosave.

**Comment by vinhdizzo** [comment]
I guess for my purposes, I can add wg-update-all-workgroup and wg-save to desktop-save-hook to have workgroups be saved across emacs instances.

What does wg do when a buffer no longer exists?  I specify desktop to only open certain types of buffers.  For example, dired buffers will not be opened in the next emacs instance.
