### ISSUE TITLE
recently visited files ring for each workgroup?

### ISSUE THREAD

**Issue by vinhdizzo** [tlh/workgroups.el#5]
I don't know if this is implemented or not, but one of the great features of escreen is that each screen has its own recently visited files ring.  So you can edit a few files in each screen, change from each, and have each screen remember the recent buffers (when switching buffers).

Is this possible with workgroups?

**Comment by tlh** [comment]
Yup.  Per-workgroup buffer-lists are in the experimental branch right now, and should be merged into master in less than a week.  They'll let you assign buffers to workgroups, and/or filter the completions presented by ido and iswitchb arbitrarily.  It's very powerful and flexible.

**Comment by vinhdizzo** [comment]
actually, i'd like to have access to all buffers in each workgroups.  i would just like to have each have their own recent files ring.

**Comment by tlh** [comment]
Oh, you will.  You can toggle filtration with C-b, and the filtration order is completely configurable: unfiltered then filtered, filtered then unfiltered, unfiltered then filtered then plain switch-to-buffer, etc.  You can specify any order, and any filters you want.

**Comment by tlh** [comment]
And one of the standard filters is `recent-files'  :)

There will be filters included that only present buffers visiting files under a certain directory, or that only present buffers with names matching a certain regexp, or that only present buffers in a certain major-mode, etc.

It's very flexible.

**Comment by tlh** [comment]
Closing this.

**Comment by vinhdizzo** [comment]
I can't imagine this whole filtering thing...guess I'll just wait to test it out once it is pushed to the main branch.

**Comment by vinhdizzo** [comment]
Just to follow up, do you have an ETA on this feature?  Thanks!

**Comment by tlh** [comment]
Heh, yeah.  See Hofstadter's Law :) The 1.0.0 release is a pretty beefy upgrade.
All I can say re: ETA is that it'll come out when it's ready -- maybe another
week or two.

**Comment by vinhdizzo** [comment]
Hi tlh,

Was this ever merged to the master branch?  Thanks!
